name: Docker & Release

on:
  push:
    branches:
      - formily_next
  workflow_dispatch: 

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore(release)')
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          ref: formily_next
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn -v
          yarn --ignore-engines
          yarn build:docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          REGISTRY: https://registry.npmjs.org

      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r formily-sites.zip doc-site

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::sites_$(date +"%Y.%m.%d_%H_%M_%S")"

      - name: GH Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: formily-sites.zip

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xbeeant/formily
          tags: latest
